---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: '{{ php.packages }}'
  when: php.packages is defined
