---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: de_DE.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: sib15-wbt, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: localhost 
mariadb:
    install: '1'
    root_password: toor
    database: db
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, libapache2-mod-php5]

